### ISSUE TITLE
Rename to velosearaptor

### ISSUE THREAD

**Issue by gunnarvoet** [modscripps/velosearaptor#38]
- [x] Change name all over the place
- [x] Move repository to modscripps account and leave gadcp as legacy version here

**Comment by gunnarvoet** [comment]
It looks like it is possible to transfer a repo to an organization and to also change its name while keeping all issues and pull requests alive on GitHub. We may need to create new forks afterwards. @jessecusack let me know when you are ready for me to do this move. No rush if you are finishing up something!

**Comment by jessecusack** [comment]
All good here, feel free to go ahead!

**Comment by gunnarvoet** [comment]
I think all the renaming has been done in #39.

**Comment by jessecusack** [comment]
Great!!
